Implement Aodh salt formula
salt-formulas/salt-formula-aodh pull request #1
Opened 2016-11-25 11:55 UTC by ityaptin

This CR adds following things:
- Configs and sls scripts for Aodh packages installation
- aodh.conf template and parameters
- Heka config for aodh logs parsing

2016-11-25 16:17 UTC, cznewt requested changes
Make config files per openstack version as other openstack services have

2016-11-25 16:23 UTC, ityaptin commented
@cznewt Hello! Aodh has been moved to separate project from Ceilometer and alarming code has been removed from Ceilometer only during Mitaka. So, from my PoV Aodh shouldn't be deployed for the earliest releases and shouldn't have a configs for it too.

2016-11-28 10:24 UTC, simonpasquier approved these changes

2016-11-28 10:24 UTC, simonpasquier commented on aodh/map.jinja
> +}, merge=salt['pillar.get']('ceilometer:server')) %}
s/ceilometer:server/aodh:server/

2016-11-28 10:25 UTC, simonpasquier requested changes
one minor comment from me.

2016-11-28 10:27 UTC, ityaptin commented on aodh/map.jinja
> +}, merge=salt['pillar.get']('ceilometer:server')) %}
I'll fix it asap

2016-11-28 10:27 UTC, simonpasquier commented on aodh/server.sls
> +{%- if server.enabled and server.version == "mitaka" %}
is it a common pattern for other OpenStack formulas to check the version?

2016-11-28 10:39 UTC, ityaptin commented on aodh/server.sls
> +{%- if server.enabled and server.version == "mitaka" %}
No, {%- if server.enabled %} is common pattern, but Aodh is supported only still Mitaka and there is not Aodh on earlier openstack versions.

2016-11-28 11:02 UTC, simonpasquier commented on aodh/server.sls
> +{%- if server.enabled and server.version == "mitaka" %}
Indeed. I was wondering about 'server.version == "mitaka"'. Adding this test will force you to update it for every new OpenStack release.

2016-11-28 13:25 UTC, simonpasquier commented on aodh/server.sls
> +{%- if server.version >= "mitaka"  %}
I wouldn't even mind about testing this. If you try to apply the aodh roles to a liberty (or earlier) environment, it should crash. But maybe @cznewt has other views...

2016-11-30 10:36 UTC, simonpasquier approved these changes

2016-11-30 14:02 UTC, elemoine requested changes

2016-11-30 14:02 UTC, elemoine commented on aodh/files/heka.toml
> +module_directory = "/usr/share/heka/lua_modules;/usr/share/heka/lua_modules/common"
You should not have this file. All the Heka configuration related to Aodh should be in `aodh/meta/heka.yml`.

2016-11-30 14:02 UTC, elemoine commented on aodh/meta/salt.yml
> +    - salt: keystone.server
Do we want that? I am not sure the `orchestrate` meta is still a thing… @cznewt?

2016-11-30 14:02 UTC, elemoine commented on aodh/meta/sphinx.yml
> +  name: Aogh
s/Aogh/Aodh?

2016-11-30 14:02 UTC, elemoine commented on metadata/service/support.yml
> +        enabled: true
You have to have a `meta/heka.yml` if you enable Heka support. For now I think I would focus on Aodh itself, and defer the support of Heka.

2016-11-30 14:37 UTC, ityaptin commented on metadata/service/support.yml
> +        enabled: true
Ok, I agree!

2016-11-30 14:45 UTC, ityaptin commented on aodh/meta/sphinx.yml
> +  name: Aogh
done

2016-11-30 14:46 UTC, ityaptin commented on aodh/files/heka.toml
> +module_directory = "/usr/share/heka/lua_modules;/usr/share/heka/lua_modules/common"
Deleted

2016-11-30 14:46 UTC, ityaptin commented on aodh/meta/salt.yml
> +    - salt: keystone.server
You are right. Deleted.

2016-11-30 16:42 UTC, merged